import {clamp,mean,poissonPmf,round,safeRatio} from './core.js';

export function eloExpected(a,b){return 1/(1+10**((b-a)/400));}
export function updateElo(rA,rB,scoreA,k=20,homeAdv=55){const e=eloExpected(rA+homeAdv,rB);return {a:rA+k*(scoreA-e),b:rB-k*(scoreA-e)};}
export function dynamicElo(history,{base=1500,k=24,decay=0.97,homeAdv=55}={}){let ratings={};for(const m of [...history].sort((a,b)=>new Date(a.date)-new Date(b.date))){const a=m.home,b=m.away;ratings[a]??=base;ratings[b]??=base;const age=Math.max(0,(Date.now()-new Date(m.date))/86400000);const w=Math.pow(decay,age/30);const kEff=k*w;const g=Math.max(1,Math.log1p(Math.abs(m.hg-m.ag)+1));const e=eloExpected(ratings[a]+homeAdv,ratings[b]);const s=m.hg>m.ag?1:m.hg===m.ag?.5:0;const d=kEff*g*(s-e);ratings[a]+=d;ratings[b]-=d;}return ratings;}
export function formIndex(matches,n=10){const ms=matches.slice(-n);if(!ms.length)return .5;const vals=ms.map(m=>m.result==='W'?1:m.result==='D'?.5:0);return mean(vals);}
export function xgStrength(matches,team,{prior=1.35,decay=.92}={}){let aw=0,ww=0,df=0,wf=0;[...matches].reverse().forEach((m,i)=>{const w=decay**i;if(m.home===team){aw+=(m.xgHome??m.hg??0)*w;df+=(m.xgAway??m.ag??0)*w;ww+=w;wf+=w;}else if(m.away===team){aw+=(m.xgAway??m.ag??0)*w;df+=(m.xgHome??m.hg??0)*w;ww+=w;wf+=w;}});return {attack:ww?aw/ww:prior,defense:wf?df/wf:prior};}
export function dixonColesTau(h,a,lh,la,rho=-.13){if(h===0&&a===0)return 1-lh*la*rho;if(h===0&&a===1)return 1+lh*rho;if(h===1&&a===0)return 1+la*rho;if(h===1&&a===1)return 1-rho;return 1;}
export function scoreMatrix(lambdaH,lambdaA,maxGoals=7,rho=-.13){const matrix=[];let total=0;for(let h=0;h<=maxGoals;h++){for(let a=0;a<=maxGoals;a++){const p=poissonPmf(h,lambdaH)*poissonPmf(a,lambdaA)*dixonColesTau(h,a,lambdaH,lambdaA,rho);matrix.push({home:h,away:a,p});total+=p;}}for(const x of matrix)x.p/=total;return matrix.sort((a,b)=>b.p-a.p);}
export function aggregateStrength({eloHome=1500,eloAway=1500,xgHome=1.35,xgAway=1.15,formHome=.5,formAway=.5,homeAdv=.08}={}){const eloEdge=(eloHome-eloAway)/400;const attackH=xgHome,attackA=xgAway;const baseH=1.35+homeAdv+0.45*eloEdge+0.35*(formHome-formAway)+(attackH-1.35)*.35;const baseA=1.15-0.18*eloEdge+0.35*(formAway-formHome)+(attackA-1.15)*.35;return {lambdaHome:clamp(baseH,.15,4.8),lambdaAway:clamp(baseA,.1,4.5)};}
export function resultProbabilities(matrix){let h=0,d=0,a=0;for(const x of matrix)x.home>x.away?h+=x.p:x.home===x.away?d+=x.p:a+=x.p;return {home:h,draw:d,away:a};}
export function goalsProbabilities(matrix){let over15=0,over25=0,over35=0,btts=0;for(const x of matrix){const g=x.home+x.away;if(g>=2)over15+=x.p;if(g>=3)over25+=x.p;if(g>=4)over35+=x.p;if(x.home>0&&x.away>0)btts+=x.p;}return {over15,over25,over35,under25:1-over25,btts,noBtts:1-btts};}
export function negativeBinomialMeanVariance(meanGoal,dispersion=1.25){return {mean:meanGoal,variance:meanGoal+meanGoal*meanGoal/dispersion};}
export function ensembleProbabilities(models,weights){const keys=Object.keys(models[0]??{});const out={};for(const k of keys)out[k]=models.reduce((s,m,i)=>s+(m[k]??0)*(weights?.[i]??1/models.length),0);return out;}
